language: ruby
rvm:
- 2.1.0
postgres:
  adapter: postgresql
  database: myapp_test
  username: postgres
before_script:
- psql -c 'create database pindd_test;' -U postgres
- rake db:migrate
env:
  matrix:
  - SECRET_KEY_BASE="$(bundle exec rake secret)"
  global:
    secure: "XV8yL9hyVeGdqkrlBnW8kWOgDwr5yA0A9naXvLYsciLOk8c2ux0BAyeFF7BTKBFqLTwie9zDvujNck68EMUL/+xSMoU8GxLMdslKljcgObMfE83iFBnY6lZODhi0Isg+hEInlYjAMl0MdlfRmlJGBEet6BEiXdbHBiLUUA2XTZY="
    secure: "ZT7yNEvmU57GLfFO+OJLBXy42A/Mk4KVrsnzO3CgNKt/hX7iBDNH9M4O9uUAj4J1H88ubaDkYA+YC3Ffx52lUrHlw43G6Bv+dTYZaRJ7cNEx1o7s3pzz+L1A3XWTz/xgFXMpWYMJ4jWQEpuccShLKKB+FUSDlpFeR9zgRgPiqmU="
